Feature/ed 9577 global settings display
ranshoshani34/elementor pull request #3
Opened 2023-02-28 07:33 UTC by mark-elementor

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-02-28 10:36 UTC, ManorHazazE requested changes

2023-02-28 10:36 UTC, ghost commented on core/kits/assets/js/hooks/ui/document/save/save/after.js
> +				id: 'elementor-save-kit-refresh-page',
Are you sure it's safe to change it?
No one using this ID?

2023-02-28 10:36 UTC, ManorHazazE commented on core/kits/documents/tabs/global-colors.php
> +				'label_on' => esc_html__( 'On', 'elementor-pro' ),
Fix domain

2023-02-28 10:36 UTC, ManorHazazE commented on core/kits/documents/tabs/global-typography.php
> +				'label_on' => esc_html__( 'On', 'elementor-pro' ),
fix domain

2023-02-28 10:36 UTC, ManorHazazE commented on core/kits/documents/tabs/global-colors.php
> +		return 'elementor/preview/style-guide/colors';
"style-guide"
"design-guidelines"
"global-style"
"styleguide"

Please choose ONE

2023-02-28 17:05 UTC, mark-elementor commented on core/kits/documents/tabs/global-colors.php
> +				'label_on' => esc_html__( 'On', 'elementor-pro' ),
Fixed.

2023-02-28 17:05 UTC, mark-elementor commented on core/kits/documents/tabs/global-typography.php
> +				'label_on' => esc_html__( 'On', 'elementor-pro' ),
Fixed.

2023-03-01 10:39 UTC, mark-elementor commented on core/kits/assets/js/hooks/ui/document/save/save/after.js
> +				id: 'elementor-save-kit-refresh-page',
I didn't find any uses. Feel quite confident to change.

2023-03-01 10:40 UTC, mark-elementor commented on core/kits/documents/tabs/global-colors.php
> +		return 'elementor/preview/style-guide/colors';
Updated everywhere possible.

2023-03-01 14:49 UTC, merged